version: '3.7'
services:
  broadcast:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: on-failure
    ports:
      - '9000:9000'
    command: [ 'sh', '-c', 'yarn broadcast' ]
    networks:
      - common_network
    volumes:
      - ./:/var/history-tools

  processor:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: on-failure
    command: [ 'sh', '-c', 'yarn processor' ]
    depends_on:
      - broadcast
      - db
    networks:
      - common_network
    volumes:
      - ./:/var/history-tools

  block_range:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: on-failure
    command: [ 'sh', '-c', 'yarn block-range' ]
    depends_on:
      - broadcast
      - db
    networks:
      - common_network
    volumes:
      - ./:/var/history-tools

  filler:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: on-failure
    command: [ 'sh', '-c', 'yarn filler' ]
    depends_on:
      - broadcast
      - db
    networks:
      - common_network
    volumes:
      - ./:/var/

  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    expose:
      - 27017
    networks:
      - common_network
    volumes:
      - database:/data/db

volumes:
  database:
networks:
  common_network:


