export enum ProcessorLabel {
  AlienWorldsActionProcessor = 'ALIEN_WORLDS_ACTION_PROCESSOR',
  AlienWorldsDeltaProcessor = 'ALIEN_WORLDS_DELTA_PROCESSOR',
  UsptsWorldsActionProcessor = 'USPTS_WORLDS_ACTION_PROCESSOR',
  UsptsWorldsDeltaProcessor = 'USPTS_WORLDS_DELTA_PROCESSOR',
  FederationActionProcessor = 'FEDERATION_ACTION_PROCESSOR',
  FederationDeltaProcessor = 'FEDERATION_DELTA_PROCESSOR',
  MFederationActionProcessor = 'M_FEDERATION_ACTION_PROCESSOR',
  MFederationDeltaProcessor = 'M_FEDERATION_DELTA_PROCESSOR',
  SFederationActionProcessor = 'S_FEDERATION_ACTION_PROCESSOR',
  SFederationDeltaProcessor = 'S_FEDERATION_DELTA_PROCESSOR',
  OtherWorldsActionProcessor = 'OTHER_WORLDS_ACTION_PROCESSOR',
  OtherWorldsDeltaProcessor = 'OTHER_WORLDS_DELTA_PROCESSOR',
  BoostWorldsActionProcessor = 'BOOST_WORLDS_ACTION_PROCESSOR',
  BoostWorldsDeltaProcessor = 'BOOST_WORLDS_DELTA_PROCESSOR',
  PtpxyWorldsActionProcessor = 'PTPXY_WORLDS_ACTION_PROCESSOR',
  PtpxyWorldsDeltaProcessor = 'PTPXY_WORLDS_DELTA_PROCESSOR',
  NftmtWorldsActionProcessor = 'NFTMT_WORLDS_ACTION_PROCESSOR',
  NftmtWorldsDeltaProcessor = 'NFTMT_WORLDS_DELTA_PROCESSOR',
  AwlndratingsActionProcessor = 'AWLNDRATINGS_ACTION_PROCESSOR',
  AwlndratingsDeltaProcessor = 'AWLNDRATINGS_DELTA_PROCESSOR',
}
