import { ProcessorLabel } from './processor/processor.labels';

export default {
  traces: [
    {
      shipTraceMessageName: ['transaction_trace_v0'],
      shipActionTraceMessageName: ['action_trace_v0', 'action_trace_v1'],
      contract: ['federation'],
      action: ['*'],
      processor: ProcessorLabel.FederationActionProcessor,
    },
    {
      shipTraceMessageName: ['transaction_trace_v0'],
      shipActionTraceMessageName: ['action_trace_v0', 'action_trace_v1'],
      contract: ['m.federation'],
      action: ['*'],
      processor: ProcessorLabel.MFederationActionProcessor,
    },
    {
      shipTraceMessageName: ['transaction_trace_v0'],
      shipActionTraceMessageName: ['action_trace_v0', 'action_trace_v1'],
      contract: ['s.federation'],
      action: ['*'],
      processor: ProcessorLabel.SFederationActionProcessor,
    },
    {
      shipTraceMessageName: ['transaction_trace_v0'],
      shipActionTraceMessageName: ['action_trace_v0', 'action_trace_v1'],
      contract: ['alien.worlds'],
      action: ['*'],
      processor: ProcessorLabel.AlienWorldsActionProcessor,
    },
    {
      shipTraceMessageName: ['transaction_trace_v0'],
      shipActionTraceMessageName: ['action_trace_v0', 'action_trace_v1'],
      contract: ['uspts.worlds'],
      action: ['*'],
      processor: ProcessorLabel.UsptsWorldsActionProcessor,
    },
    {
      shipTraceMessageName: ['transaction_trace_v0'],
      shipActionTraceMessageName: ['action_trace_v0', 'action_trace_v1'],
      contract: ['other.worlds'],
      action: ['*'],
      processor: ProcessorLabel.OtherWorldsActionProcessor,
    },
    {
      shipTraceMessageName: ['transaction_trace_v0'],
      shipActionTraceMessageName: ['action_trace_v0', 'action_trace_v1'],
      contract: ['boost.worlds'],
      action: ['*'],
      processor: ProcessorLabel.BoostWorldsActionProcessor,
    },
    {
      shipTraceMessageName: ['transaction_trace_v0'],
      shipActionTraceMessageName: ['action_trace_v0', 'action_trace_v1'],
      contract: ['ptpxy.worlds'],
      action: ['*'],
      processor: ProcessorLabel.PtpxyWorldsActionProcessor,
    },
    {
      shipTraceMessageName: ['transaction_trace_v0'],
      shipActionTraceMessageName: ['action_trace_v0', 'action_trace_v1'],
      contract: ['nftmt.worlds'],
      action: ['*'],
      processor: ProcessorLabel.NftmtWorldsActionProcessor,
    },
    {
      shipTraceMessageName: ['transaction_trace_v0'],
      shipActionTraceMessageName: ['action_trace_v0', 'action_trace_v1'],
      contract: ['awlndratings'],
      action: ['*'],
      processor: ProcessorLabel.AwlndratingsActionProcessor,
    },
  ],
  deltas: [
    {
      shipDeltaMessageName: ['table_delta_v0'],
      name: ['contract_row'],
      code: ['federation'],
      scope: ['*'],
      table: ['*'],
      processor: ProcessorLabel.FederationDeltaProcessor,
    },
    {
      shipDeltaMessageName: ['table_delta_v0'],
      name: ['contract_row'],
      code: ['m.federation'],
      scope: ['*'],
      table: ['*'],
      processor: ProcessorLabel.MFederationDeltaProcessor,
    },
    {
      shipDeltaMessageName: ['table_delta_v0'],
      name: ['contract_row'],
      code: ['s.federation'],
      scope: ['*'],
      table: ['*'],
      processor: ProcessorLabel.SFederationDeltaProcessor,
    },
    {
      shipDeltaMessageName: ['table_delta_v0'],
      name: ['contract_row'],
      code: ['alien.worlds'],
      scope: ['*'],
      table: ['*'],
      processor: ProcessorLabel.AlienWorldsDeltaProcessor,
    },
    {
      shipDeltaMessageName: ['table_delta_v0'],
      name: ['contract_row'],
      code: ['uspts.worlds'],
      scope: ['*'],
      table: ['*'],
      processor: ProcessorLabel.UsptsWorldsDeltaProcessor,
    },
    {
      shipDeltaMessageName: ['table_delta_v0'],
      name: ['contract_row'],
      code: ['other.worlds'],
      scope: ['*'],
      table: ['*'],
      processor: ProcessorLabel.OtherWorldsDeltaProcessor,
    },
    {
      shipDeltaMessageName: ['table_delta_v0'],
      name: ['contract_row'],
      code: ['boost.worlds'],
      scope: ['*'],
      table: ['*'],
      processor: ProcessorLabel.BoostWorldsDeltaProcessor,
    },
    {
      shipDeltaMessageName: ['table_delta_v0'],
      name: ['contract_row'],
      code: ['ptpxy.worlds'],
      scope: ['*'],
      table: ['*'],
      processor: ProcessorLabel.PtpxyWorldsDeltaProcessor,
    },
    {
      shipDeltaMessageName: ['table_delta_v0'],
      name: ['contract_row'],
      code: ['nftmt.worlds'],
      scope: ['*'],
      table: ['*'],
      processor: ProcessorLabel.NftmtWorldsDeltaProcessor,
    },
    {
      shipDeltaMessageName: ['table_delta_v0'],
      name: ['contract_row'],
      code: ['awlndratings'],
      scope: ['*'],
      table: ['*'],
      processor: ProcessorLabel.AwlndratingsDeltaProcessor,
    },
  ],
};
